name: CI

permissions:
  contents: write

on: [push, pull_request]

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set-Up
        run: sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          version: latest

      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly

      - name: Install Dylint
        run: cargo install dylint-link

      - name: Install Cargo Dylint
        run: cargo install cargo-dylint

      - name: Install Toolchain Nightly
        run: rustup toolchain install nightly

      - name: RustUp Wasm Target
        run: rustup target add wasm32-unknown-unknown

      - name: Rustup component
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Build Std
        run: cargo build -Zbuild-std

      - name: Build project
        run: cargo build --release --locked
      - name: Bump version and push tag/create release point
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
        id: bump_version
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/alemanes
          asset_name: alemanes-linux-amd64
          tag: ${{ steps.bump_version.outputs.new_tag }}
          overwrite: true
