name: CI

permissions:
  contents: write

#on: [push, pull_request]
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '**'
jobs:
  release:
    name: Build and Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/<name>
            asset_name: <name>-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/<name>.exe
            asset_name: <name>-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/<name>
            asset_name: <name>-macos
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set-Up
        run: sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          version: latest

      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly

      - name: Install Dylint
        run: cargo install dylint-link

      - name: Install Cargo Dylint
        run: cargo install cargo-dylint

      - name: Install Toolchain Nightly
        run: rustup toolchain install nightly

      - name: RustUp
        run: rustup update

      - name: RustUp Nightly
        run: rustup update nightly

      - name: RustUp Wasm Target
        run: rustup target add wasm32-unknown-unknown --toolchain nightly

      - name: Rustup component
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Submodule Update
        run: git submodule update --init --recursive

      - name: Build project
        run: cargo build --release
      - name: Bump version and push tag/create release point
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
        id: bump_version
      #- name: Make Binary Unix Executable
      #  run:  sudo chmod 755 target/release/substrate-contracts-node
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Webb Substrate contract Node release"
